# Generated by Django 5.0.6 on 2024-07-12 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('nombre_comprador', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_comprador', models.CharField(blank=True, max_length=100, null=True)),
                ('email_comprador', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='instrumento')),
                ('descripcion', models.TextField()),
                ('yt_iframe', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_instrumento',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id_disco', models.AutoField(primary_key=True, serialize=False)),
                ('artista', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='disco')),
                ('descripcion', models.TextField()),
                ('spotify_iframe', models.TextField(blank=True, null=True)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='app.carrito')),
                ('disco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disco')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instrumento')),
            ],
        ),
        migrations.AddField(
            model_name='instrumento',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='app.tipo_instrumento'),
        ),
    ]
